sudo: required
language: node_js
node_js:
  - "6.9.4"
addons:
  code_climate:
    repo_token: 7379e1389628414ab9776118fe8ca691ad932d31eb4a52fae43120574a7895eb
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info

notifications:
  webhooks:
    urls:
      - https://api.netlify.com/build_hooks/58c112868906b638870b5448
    on_success: always # default: always
    on_failure: never # default: always
    on_start: never   # default: never
